name: Docker Image CI

on:
  push:
    branches: [ main ]
  schedule:
  - cron: "0 0 * * 0"


jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Build and Push to GitHub Packages
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: whi-tw/node-red-docker:latest
